### ISSUE TITLE
No Such Function matches

### ISSUE THREAD

**Issue by QianmuZ** [godfather1103/p3c#2]
idea.log:

Exception applying rule PackageNamingRule on file

java.lang.RuntimeException: org.jaxen.UnresolvableException: No Such Function matches
	at net.sourceforge.pmd.lang.rule.xpath.JaxenXPathRuleQuery.evaluate(JaxenXPathRuleQuery.java:73)
	at net.sourceforge.pmd.lang.rule.XPathRule.evaluate(XPathRule.java:114)
	at net.sourceforge.pmd.lang.java.rule.JavaRuleChainVisitor.visit(JavaRuleChainVisitor.java:42)
	at net.sourceforge.pmd.lang.rule.AbstractRuleChainVisitor.visitAll(AbstractRuleChainVisitor.java:96)
	at net.sourceforge.pmd.RuleChain.apply(RuleChain.java:67)
	at net.sourceforge.pmd.RuleSets.apply(RuleSets.java:140)
	at com.alibaba.p3c.idea.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.kt:216)
	at com.alibaba.p3c.idea.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.kt:61)
	at com.alibaba.p3c.idea.pmd.AliPmdProcessor.processFile(AliPmdProcessor.kt:67)

**Comment by godfather1103** [comment]
IDEA版本，跟重现步骤有吗？

**Comment by QianmuZ** [comment]
> IDEA版本，跟重现步骤有吗？

idea:2023.2
重现步骤：这个不清楚，只是从idea日志中频繁报错，好像idea 保存文件的时候会触发，这个不太确定。

Caused by: org.jaxen.UnresolvableException: No Such Function matches
	at org.jaxen.SimpleFunctionContext.getFunction(SimpleFunctionContext.java:127)
	at org.jaxen.ContextSupport.getFunction(ContextSupport.java:242)
	at org.jaxen.Context.getFunction(Context.java:216)
	at org.jaxen.expr.DefaultFunctionCallExpr.evaluate(DefaultFunctionCallExpr.java:176)
	at org.jaxen.expr.DefaultFunctionCallExpr.evaluateParams(DefaultFunctionCallExpr.java:195)
	at org.jaxen.expr.DefaultFunctionCallExpr.evaluate(DefaultFunctionCallExpr.java:179)
	at org.jaxen.expr.DefaultPredicate.evaluate(DefaultPredicate.java:95)
	at org.jaxen.expr.PredicateSet.applyPredicate(PredicateSet.java:269)
	at org.jaxen.expr.PredicateSet.evaluatePredicates(PredicateSet.java:244)
	at org.jaxen.expr.DefaultNameStep.evaluate(DefaultNameStep.java:215)
	at org.jaxen.expr.DefaultLocationPath.evaluate(DefaultLocationPath.java:140)
	at org.jaxen.expr.DefaultXPathExpr.asList(DefaultXPathExpr.java:102)
	at org.jaxen.BaseXPath.selectNodesForContext(BaseXPath.java:677)
	at org.jaxen.BaseXPath.selectNodes(BaseXPath.java:216)
	at net.sourceforge.pmd.lang.rule.xpath.JaxenXPathRuleQuery.evaluate(JaxenXPathRuleQuery.java:69)

**Comment by godfather1103** [comment]
右下角有报错吗？是否影响什么功能？只是日志文件有输出异常日志吗？

**Comment by godfather1103** [comment]
我看了一下我本地idea.log,发现里面也有对应的日志输出，但是目前没有出现影响使用的情况，所以不打算修复该问题
